angular
  .module('app')
  .controller('expertiseCtrl', function( $scope ){
       $scope.expertises = [
         {
           name:"程式語言",
           left:[
             "HTML","CSS3","javascript","AngularJS"
           ],
           right:[
             "jQuery","ReactJS","PHP"
           ]
         },
         {
           name:"版本控管",
           left:[
             "svn"
           ],
           right:[
             "git"
           ]
         },
         {
           name:"開發工具",
           left:[
             "Sublime"
           ],
           right:[
             "Atom"
           ]
         },
         {
           name:"設計軟體",
           left:[
             "Photoshop"
           ],
           right:[
             "Illustrator"
           ]
         },
         {
           name:"遊戲開發",
           left:[
             "Unity"
           ],
           right:[
             "Arduino"
           ]
         }
       ]
  })
